version: "3.8"

services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - translator-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - 5432

  migrations:
    image: flyway/flyway
    volumes:
      - ./migrations/db:/flyway/sql
    command: migrate
    env_file:
      - .env
    environment:
      FLYWAY_URL: jdbc:postgresql://${DB_HOST}:5432/${DB_DATABASE}
      FLYWAY_USER: ${DB_USERNAME}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
      FLYWAY_DEFAULT_SCHEMA: ${DB_SCHEMA}
    depends_on:
      - db

volumes:
